blueprint:
  name: Nordpool Dynamic Price Automation (2026)
  description: Turns devices on/off based on total price including variable VAT and fixed fees.
  domain: automation
  input:
    nordpool_config_entry_id:
      name: Nord Pool Configuration Entry ID
      description: "Find this ID in Developer Tools > Actions > Nord Pool: Get prices (YAML mode)"
      selector:
        text:
    hour_rank:
      name: Hours on
      default: 12
      selector:
        number:
          min: 0.0
          max: 24.0
          mode: slider
          step: 1.0
    hour_ratio:
      name: Hour percent
      default: 50
      selector:
        number:
          min: 0.0
          max: 100.0
          mode: slider
          step: 5.0
    # New Input Field for VAT/Moms
    vat_multiplier:
      name: VAT Multiplier (e.g., 1.25 for 25% moms, 1.0 for 0%)
      default: 1.25
      selector:
        number:
          min: 1.0
          max: 2.0
          step: 0.01
    # New Input Field for Fixed Fees (e.g., Grid fees, certificates)
    fixed_fees_per_kwh:
      name: Fixed Fees per kWh (in your local currency, e.g., SEK 0.125)
      default: 0.125
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.001
    allways_on:
      name: Always on price (Local Currency/kWh)
      default: 0.0
      selector:
        number:
          min: 0.0
          max: 10.0
          mode: slider
          step: 0.05
    allways_off:
      name: Always off price (Local Currency/kWh)
      default: 2.5
      selector:
        number:
          min: 0.0
          max: 10.0
          mode: slider
          step: 0.05
    turnon:
      name: Turn On Actions
      default: []
      selector:
        action: {}
    turnoff:
      name: Turn Off Actions
      default: []
      selector:
        action: {}

variables:
  # Map inputs to variables
  hour_rank_input: !input hour_rank
  hour_ratio_var: !input hour_ratio
  allways_on_var: !input allways_on
  allways_off_var: !input allways_off
  vat_multiplier_var: !input vat_multiplier
  fixed_fees_var: !input fixed_fees_per_kwh

trigger:
  - platform: time_pattern
    minutes: "/15"

action:
  - action: nordpool.get_prices_for_date
    data:
      config_entry: !input nordpool_config_entry_id
      date: "{{ now().date() }}"
    response_variable: daily_data

  - variables:
      # 1. Process prices and store as a clean list of floats
      prices_total: >
        {% set region = daily_data.keys() | first %}
        {% set ns = namespace(p=[]) %}
        {% for item in daily_data[region] %}
          {% set spot_kwh = item.price | float(0) / 1000 %}
          {% set total = (spot_kwh * (vat_multiplier_var | float(1.0))) + (fixed_fees_var | float(0)) %}
          {% set ns.p = ns.p + [total | round(4)] %}
        {% endfor %}
        {{ ns.p }}
      
      # 2. Get current price index (supports 15-min or 60-min data)
      idx: >
        {% set count = prices_total | length %}
        {% if count > 24 %}
          {{ (now().hour * 4) + (now().minute // 15) }}
        {% else %}
          {{ now().hour }}
        {% endif %}

      # 3. Define price and sorted list
      price: "{{ prices_total[idx | int] | float(0) if (idx | int) < (prices_total | length) else prices_total[-1] | float(0) }}"
      sorted_prices: "{{ prices_total | sort | list }}"

      # 4. FIXED MATH: Use 'min' and 'max' filters to get single float values for subtraction
      min_p: "{{ sorted_prices | min | float(0) }}"
      max_p: "{{ sorted_prices | max | float(0) }}"
      
      above_low: "{{ (price | float(0)) - (min_p | float(0)) }}"
      diff: "{{ (max_p | float(0)) - (min_p | float(0)) }}"
      
      # 5. Calculation of Rank and Ratio
      ratio: "{{ ( (above_low | float / diff | float) * 100 ) | round if diff | float > 0 else 0 }}"
      rank: "{{ (sorted_prices.index(price | float) + 1) | int if price in sorted_prices else 99 }}"
      
      # 6. Final Result
      condition_rank: "{{ rank | int <= (hour_rank_input | float * (prices_total | length / 24)) | int }}"
      seton: >
        {{ price <= (allways_on_var | float(0)) or 
           (ratio | int <= (hour_ratio_var | int)) or 
           condition_rank }}
      result: "{{ price < (allways_off_var | float(0)) and seton }}"

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ result }}"
        sequence: !input turnon
    default: !input turnoff

mode: single
